name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-posix:
    name: Tests on Posix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Instrument code
      uses: AryazE/auto-dylin/instrument@main
      with:
        analysis-coverage: false
    - name: Run tests with coverage
      run: pytest -n 4
    - name: Report results
      if: always()
      uses: AryazE/auto-dylin/report@main